
add_newline = true
command_timeout = 1000
#format = """$hostname$os$kubernetes$directory$git_branch $git_status"""

format = """
[â•­â”€](bold #5AC8FF) $hostname$os$shell$conda$python$nodejs
[â•°â”€](bold #5AC8FF) $directory$git_branch$git_status
"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''

#--
[os]
format = '[$symbol](bold #5AC8FF)'
disabled = false

[os.symbols]
Windows = 'î˜ª '
Arch = 'ó°£‡ '
Ubuntu = 'ïŒ› '
Macos = 'ó°€µ '

# ---y

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold #905AFF) on '
disabled = false

# Shows current directory
[directory]
truncation_length = 1
truncation_symbol = '../'
home_symbol = 'ó°‹œ ~'
read_only_style = '197'
read_only = ' ï€£ '
format = 'at [$path](bold #5AC8FF)[$read_only](#F1F1F1)($read_only_style) '

# Shows current git branch
[git_branch]
symbol = 'î‚  '
format = 'via [$symbol$branch](bold #905AFF)'
# truncation_length = 4
truncation_symbol = 'â€¦/'

# Shows current git status
[git_status]
format = ' [$all_status$ahead_behind](bold #905AFF) '
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
renamed = 'ïª¶ '
deleted = 'ï€” '

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [ó±ƒ¾ $context\($namespace\)](bold purple) '
disabled = true

# Shows conda environment
[conda]
format = 'via [$symbol$environment](bold #77DD77) '

# Shows active shell
[shell]
format = "[$indicator](bold #5AC8FF)"
fish_indicator = 'ó°ˆº'
bash_indicator = 'bash'
disabled = false

# ---

[docker_context]
disabled = true

[python]
disabled = false
format = ' via [ğŸ $version](bold #77DD77) '

[nodejs]
disabled = false
format = ' via [ğŸ¤– $version](bold #6495ed) '

